#include "subdivision.hpp"
#include "geometrycentral/surface/surface_mesh_factories.h"
#include "geometrycentral/utilities/vector3.h"

namespace geometry
{

MeshAndGeometry catmull_clark_subdivision(std::unique_ptr<geometrycentral::surface::ManifoldSurfaceMesh> mesh,
                                          std::unique_ptr<geometrycentral::surface::VertexPositionGeometry> geometry)
{
    std::vector<geometrycentral::Vector3> new_points;
    new_points.reserve(mesh->nFaces() + mesh->nEdges() + mesh->nVertices());
    // Maps the face f to the index of it's corresponding new point in the new_points vector
    // i.e. new_points[old_face_new_point_index[f]] stores the new point generated by f
    std::unordered_map<geometrycentral::surface::Face, std::size_t> old_face_new_point_index;

    for (std::size_t face_id = 0; geometrycentral::surface::Face face : mesh->faces())
    {
        auto new_face_point{geometrycentral::Vector3::zero()};
        std::size_t num_vertices{0};
        for (geometrycentral::surface::Vertex vertex : face.adjacentVertices())
        {
            new_face_point += geometry->vertexPositions[vertex];
            ++num_vertices;
        }
        old_face_new_point_index.emplace(face, new_points.size());
        new_points.emplace_back(new_face_point / num_vertices);
        ++face_id;
    }

    // For each edge, add an edge point
    std::unordered_map<geometrycentral::surface::Edge, std::size_t> old_edge_new_point_index;
    std::unordered_map<geometrycentral::surface::Edge, geometrycentral::Vector3> old_edge_midpoints;
    for (std::size_t edge_id = 0; geometrycentral::surface::Edge edge : mesh->edges())
    {
        const auto endpoints_sum{geometry->vertexPositions[edge.secondVertex()] +
                                 geometry->vertexPositions[edge.firstVertex()]};
        old_edge_midpoints.emplace(edge, endpoints_sum / 2);

        auto new_edge_point{geometrycentral::Vector3::zero()};
        new_edge_point += endpoints_sum;
        for (geometrycentral::surface::Face face : edge.adjacentFaces())
        {
            new_edge_point += new_points[old_face_new_point_index[face]];
        }
        old_edge_new_point_index.emplace(edge, new_points.size());
        new_points.emplace_back(new_edge_point / 4.0);
        ++edge_id;
    }

    std::unordered_map<geometrycentral::surface::Vertex, std::size_t> old_vertex_new_point_index;
    for (std::size_t vertex_id = 0; geometrycentral::surface::Vertex vertex : mesh->vertices())
    {
        auto avg_new_face_points{geometrycentral::Vector3::zero()};
        std::size_t num_faces{0};
        for (geometrycentral::surface::Face face : vertex.adjacentFaces())
        {
            avg_new_face_points += new_points[old_face_new_point_index[face]];
            ++num_faces;
        }
        avg_new_face_points /= num_faces;
        ++vertex_id;

        auto avg_old_edge_midpoints{geometrycentral::Vector3::zero()};
        std::size_t num_edges{0};
        for (geometrycentral::surface::Edge edge : vertex.adjacentEdges())
        {
            avg_old_edge_midpoints += old_edge_midpoints[edge];
            ++num_edges;
        }
        avg_old_edge_midpoints /= num_edges;
        if (num_faces != num_edges)
        {
            throw std::runtime_error{"ERROR! num_faces != num_edges"};
        }

        const auto& current_vertex{geometry->vertexPositions[vertex]};
        old_vertex_new_point_index.emplace(vertex, new_points.size());
        new_points.emplace_back((avg_new_face_points / num_faces) + (2 * avg_old_edge_midpoints / num_faces) +
                                ((static_cast<double>(num_faces - 3) / (num_faces)) * current_vertex));
    }

    std::vector<std::vector<std::size_t>> new_faces_indices;
    for (geometrycentral::surface::Face face : mesh->faces())
    {
        const std::size_t new_face_index{old_face_new_point_index[face]};
        for (geometrycentral::surface::Halfedge halfedge : face.adjacentHalfedges())
        {
            new_faces_indices.emplace_back(std::vector<std::size_t>{
                old_vertex_new_point_index[halfedge.vertex()], old_edge_new_point_index[halfedge.edge()],
                new_face_index, old_edge_new_point_index[halfedge.next().next().next().edge()]});
        }
    }

    return geometrycentral::surface::makeManifoldSurfaceMeshAndGeometry(new_faces_indices, new_points);
}

} // namespace geometry